version: '3.3'

services:
  tracks-fe-prod:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    image: tracks-fe:221123
    environment:
      - HOSTNAME=${HOSTNAME}
      - PORT=${PORT}
    ports:
      - 3001:3000