version: '3.3'

# DEV.MODE
services:
  tracks-fe:
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    volumes:
      - .:/app/frontend
    environment:
      - HOSTNAME=${HOSTNAME}
      - PORT=${PORT}
    ports:
      - 3000:3000
  tracks-fe-story:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    restart: always
    volumes:
      - .:/tmp
    environment:
      - HOSTNAME=${HOSTNAME}
      - PORT=${PORT}
    ports:
      - 6006:6006